# Generated by Django 6.0.4 on 2026-04-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0006_auditlog_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('month', models.DateField(verbose_name='Mois')),
                (
                    'total_interviews',
                    models.PositiveIntegerField(default=0, verbose_name='Total Entretiens'),
                ),
                (
                    'total_hires',
                    models.PositiveIntegerField(default=0, verbose_name='Total Recrutements'),
                ),
                (
                    'total_registrations',
                    models.PositiveIntegerField(default=0, verbose_name='Total Inscriptions'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_set',
                        to='accounts.company',
                        verbose_name='Société',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Instantané KPI',
                'verbose_name_plural': 'Instantanés KPI',
                'ordering': ['-month'],
                'unique_together': {('company', 'month')},
            },
        ),
    ]
