# Generated by Django 4.2.30 on 2026-04-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistiques", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="kpisnapshot",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="kpisnapshot",
            name="month",
            field=models.DateField(unique=True, verbose_name="Mois"),
        ),
        migrations.RemoveField(
            model_name="kpisnapshot",
            name="company",
        ),
    ]
