# Tests generated by AI
from unittest.mock import MagicMock, patch

from django.test import TestCase

from apps.ia.exceptions import CVUnsupportedFormatError
from apps.ia.extractors import CVTextExtractor
from apps.ia.scorer import CompatibilityScorer


class CompatibilityScorerTest(TestCase):
    def setUp(self):
        self.scorer = CompatibilityScorer()

    def test_perfect_match(self):
        """Test scoring when CV perfectly matches the offer's requirements."""
        cv_data = MagicMock(
            competences_extraites=['Python', 'Django', 'React'], experience_annees=5
        )
        offre = MagicMock(competences=['Python', 'Django', 'React'], experience_requise=5)

        result = self.scorer.calculate_score(cv_data, offre)

        self.assertGreaterEqual(result['score_global'], 90)
        self.assertEqual(len(result['matching_competences']), 3)
        self.assertEqual(len(result['missing_competences']), 0)

    def test_experience_weight(self):
        """Test scoring when experience is below requirement."""
        cv_data = MagicMock(
            competences_extraites=['Python', 'Django', 'React'], experience_annees=2
        )
        offre = MagicMock(competences=['Python', 'Django', 'React'], experience_requise=4)

        result = self.scorer.calculate_score(cv_data, offre)

        # Experience score should be around 50% (2/4)
        self.assertEqual(result['score_experience'], 50.0)
        self.assertLess(result['score_global'], 100)

    def test_missing_competences(self):
        """Test scoring when some competences are missing."""
        cv_data = MagicMock(competences_extraites=['Python'], experience_annees=5)
        offre = MagicMock(competences=['Python', 'Django', 'React'], experience_requise=5)

        result = self.scorer.calculate_score(cv_data, offre)

        self.assertEqual(len(result['matching_competences']), 1)
        self.assertEqual(len(result['missing_competences']), 2)
        self.assertLess(result['score_competences'], 50)


class CVExtractorTest(TestCase):
    def setUp(self):
        self.extractor = CVTextExtractor()

    def test_unsupported_format(self):
        """Test that unsupported formats raise CVUnsupportedFormatError."""
        with self.assertRaises(CVUnsupportedFormatError):
            self.extractor.extract('test.txt')

    @patch('PyPDF2.PdfReader')
    @patch('builtins.open', create=True)
    def test_pdf_extraction_mock(self, mock_open, mock_pdf_reader):
        """Test mocked PDF text extraction."""
        mock_pdf_reader.return_value.pages = [
            MagicMock(extract_text=lambda: 'This is a CV with Python skills.')
        ]

        text = self.extractor.extract('test.pdf')
        self.assertIn('Python', text)
