# Generated by Django 6.0.4 on 2026-04-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ia', '0002_cvdata_resume_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdata',
            name='questions_ia',
            field=models.JSONField(
                default=list,
                help_text="Questions d'entretien suggérées par l'IA.",
                verbose_name="Questions d'entretien IA",
            ),
        ),
    ]
