# Generated by Django 6.0.4 on 2026-05-17 20:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('statut', models.CharField(choices=[('planifie', 'Planifie'), ('termine', 'Termine'), ('annule', 'Annule')], default='planifie', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('commentaires', models.TextField(blank=True)),
                ('recommandation', models.TextField(blank=True)),
                ('score_communication', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_competences', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_motivation', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_global', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='candidatures.candidature')),
                ('evaluateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens_evalues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
    ]
