# Generated by Django 4.2.30 on 2026-05-18 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretiens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='points_amelioration',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entretien',
            name='points_forts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entretien',
            name='score_adaptabilite',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='entretien',
            name='score_culture_fit',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
