# Generated by Django 6.0.4 on 2026-04-14 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('entretiens', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='entretien',
            new_name='entretiens__recrute_6ed91e_idx',
            old_name='entretiens__recrute_idx',
        ),
        migrations.RenameIndex(
            model_name='entretien',
            new_name='entretiens__candida_73bb9d_idx',
            old_name='entretiens__candida_idx',
        ),
    ]
