# Generated by Django 6.0.4 on 2026-04-18 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0006_auditlog_company'),
        (
            'entretiens',
            '0002_rename_entretiens__recrute_idx_entretiens__recrute_6ed91e_idx_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='company',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(class)s_set',
                to='accounts.company',
                verbose_name='Société',
            ),
            preserve_default=False,
        ),
    ]
