# Generated by Django 6.0.4 on 2026-04-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entretiens', '0003_entretien_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectifEntretien',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('titre', models.CharField(max_length=255, verbose_name='Objectif')),
                ('est_atteint', models.BooleanField(default=False, verbose_name='Atteint')),
                (
                    'entretien',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='objectifs',
                        to='entretiens.entretien',
                        verbose_name='Entretien',
                    ),
                ),
            ],
            options={
                'verbose_name': "Objectif d'entretien",
                'verbose_name_plural': "Objectifs d'entretien",
            },
        ),
    ]
