# Generated by Django 6.0.4 on 2026-04-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entretiens', '0004_objectifentretien'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='resume_ia',
            field=models.TextField(blank=True, verbose_name='Résumé IA'),
        ),
    ]
