# Generated by Django 4.2.30 on 2026-04-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entretiens", "0005_entretien_resume_ia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entretien",
            name="company",
        ),
    ]
