# Generated by Django 6.0.4 on 2026-05-17 20:55

import apps.candidatures.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(upload_to=apps.candidatures.models.cv_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('preselectionne', 'Preselectionne'), ('rejete', 'Rejete'), ('accepte', 'Accepte')], default='en_attente', max_length=20)),
                ('matching_score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='offres.offre')),
            ],
            options={
                'ordering': ['-date_soumission'],
                'unique_together': {('offre', 'candidat')},
            },
        ),
    ]
