# Generated by Django 4.2 on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='ai_extracted_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='candidature',
            name='ai_summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidature',
            name='cv_text',
            field=models.TextField(blank=True),
        ),
    ]
