# Generated by Django 6.0.4 on 2026-04-14 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('candidatures', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='candidature',
            new_name='candidature_statut_78629d_idx',
            old_name='candidature_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='candidature',
            new_name='candidature_score_i_761fb9_idx',
            old_name='candidature_score_ia_idx',
        ),
    ]
