# Generated by Django 6.0.4 on 2026-04-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'candidatures',
            '0002_rename_candidature_statut_idx_candidature_statut_78629d_idx_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='experience_annees',
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Années d'expérience (déclarées)"
            ),
        ),
        migrations.AddField(
            model_name='candidature',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Profil LinkedIn'),
        ),
    ]
