# Generated by Django 4.2.30 on 2026-05-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0002_candidature_simple_ai_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='message',
        ),
        migrations.AddField(
            model_name='candidature',
            name='experience_annees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidature',
            name='lettre_motivation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
