# Tests generated by AI
from unittest.mock import patch

from django.contrib.auth import get_user_model
from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import Client, TestCase
from django.urls import reverse

from apps.candidatures.models import Candidature
from apps.offres.models import Offre

User = get_user_model()


class CandidatureUploadTest(TestCase):
    def setUp(self):
        self.client = Client()
        self.user = User.objects.create_user(
            email='candidat@example.com',
            nom='Candidat',
            prenom='User',
            password='password123',
            role='candidat',
            is_active=True,
        )
        self.offre = Offre.objects.create(
            titre='Python Developer',
            description='Django expert needed',
            type_contrat='CDI',
            statut='publiee',
            created_by=self.user,  # Not realistic but works for setup
        )
        self.upload_url = reverse('candidat:upload')
        self.client.login(username='candidat@example.com', password='password123')

    @patch('apps.ia.tasks.analyze_cv.delay')
    def test_ajax_upload_success(self, mock_analyze_cv):
        """Test successful CV upload via AJAX."""
        # Add PDF magic bytes to pass validator
        cv_content = b'%PDF-1.4\nDummy CV content'
        cv_file = SimpleUploadedFile('cv.pdf', cv_content, content_type='application/pdf')

        response = self.client.post(
            self.upload_url, {'offre_id': self.offre.id, 'cv_file': cv_file}
        )

        self.assertEqual(response.status_code, 200)
        data = response.json()
        self.assertTrue(data['success'])

        # Verify candidature was created
        self.assertEqual(Candidature.objects.count(), 1)
        candidature = Candidature.objects.first()
        self.assertEqual(candidature.offre, self.offre)
        self.assertEqual(candidature.candidat, self.user)

        # Verify IA task was triggered
        mock_analyze_cv.assert_called_once_with(candidature.id)

    def test_duplicate_application_blocked(self):
        """Test that a candidate cannot apply twice to the same offer."""
        # Create first application
        Candidature.objects.create(
            offre=self.offre, candidat=self.user, cv_file_original_name='cv1.pdf'
        )

        cv_file = SimpleUploadedFile('cv2.pdf', b'Content', content_type='application/pdf')
        response = self.client.post(
            self.upload_url, {'offre_id': self.offre.id, 'cv_file': cv_file}
        )

        self.assertEqual(response.status_code, 400)
        self.assertIn('déjà postulé', response.json()['error'])
