# Generated by Django 6.0.4 on 2026-04-14 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='evaluation',
            new_name='evaluations_statut_88e7a4_idx',
            old_name='evaluations_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='evaluation',
            new_name='evaluations_recomma_1ee72e_idx',
            old_name='evaluations_recommandation_idx',
        ),
    ]
