# Tests generated by AI
from io import BytesIO
from unittest.mock import MagicMock

from django.test import TestCase
from django.utils import timezone

from apps.rapports.pdf_generator import EvaluationPDFGenerator


class EvaluationPDFGeneratorTest(TestCase):
    def setUp(self):
        self.generator = EvaluationPDFGenerator()

    def test_pdf_generation(self):
        """Test that the PDF is generated and returned as a BytesIO buffer."""
        # Create a mock Evaluation object
        mock_eval = MagicMock()
        mock_eval.entretien.candidat.get_full_name = 'John Doe'
        mock_eval.entretien.candidature.offre.titre = 'Senior Dev'
        mock_eval.entretien.date_heure = timezone.now()

        mock_eval.competences_rate = 4
        mock_eval.communication_rate = 5
        mock_eval.motivation_rate = 4
        mock_eval.adaptabilite_rate = 3
        mock_eval.culture_fit_rate = 5
        mock_eval.moyenne_score = 4.2

        mock_eval.commentaires = 'Excellent candidat avec une bonne expérience.'
        mock_eval.points_forts = 'Compétences techniques'
        mock_eval.points_amelioration = 'Communication en anglais'
        mock_eval.recommandation = 'retenu'
        mock_eval.get_recommandation_display.return_value = 'Retenu'

        # Test PDF Generation
        # _radar_chart uses 'Agg' backend, so it's safe to run headlessly during tests
        buffer = self.generator.generate(mock_eval)

        # Check the result
        self.assertIsInstance(buffer, BytesIO)
        self.assertGreater(len(buffer.getvalue()), 100)  # PDF has content
