# Tests generated by AI - DRF endpoints
from django.contrib.auth import get_user_model
from django.test import Client, TestCase

User = get_user_model()


class RBACRoleTest(TestCase):
    def setUp(self):
        self.client = Client()
        self.admin = User.objects.create_user(
            email='admin@example.com',
            nom='Admin',
            prenom='User',
            password='password123',
            role='admin',
            is_active=True,
        )
        self.rh = User.objects.create_user(
            email='rh@example.com',
            nom='RH',
            prenom='User',
            password='password123',
            role='rh',
            is_active=True,
        )
        self.candidat = User.objects.create_user(
            email='candidat@example.com',
            nom='Candidat',
            prenom='User',
            password='password123',
            role='candidat',
            is_active=True,
        )

        self.offres_list_url = '/api/offres/'

    def test_rh_access_to_offres_api(self):
        """RH should have access to list job offers."""
        self.client.login(username='rh@example.com', password='password123')
        response = self.client.get(self.offres_list_url)
        self.assertEqual(response.status_code, 200)