# Tests generated by AI
from unittest.mock import Mock

from django.test import SimpleTestCase

from apps.statistiques.chart_generator import DashboardChartGenerator


class DashboardChartGeneratorTests(SimpleTestCase):
    def test_score_distribution_returns_base64_for_scored_candidatures(self):
        generator = DashboardChartGenerator()
        candidatures_qs = Mock()
        scored_qs = Mock()

        candidatures_qs.exclude.return_value = scored_qs
        scored_qs.values_list.return_value = [12, 35, 48, 77, 92, 100]

        chart = generator.score_distribution(candidatures_qs)

        self.assertTrue(chart)
        candidatures_qs.exclude.assert_called_once_with(score_ia__isnull=True)
        scored_qs.values_list.assert_called_once_with('score_ia', flat=True)
