# Generated by Django 6.0.4 on 2026-04-14 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='offre',
            new_name='offres_offr_statut_957e61_idx',
            old_name='offres_offre_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='offre',
            new_name='offres_offr_type_co_cb9f8c_idx',
            old_name='offres_offre_type_contrat_idx',
        ),
    ]
