# Generated by Django 6.0.4 on 2026-04-18 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0006_auditlog_company'),
        ('offres', '0002_rename_offres_offre_statut_idx_offres_offr_statut_957e61_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='company',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(class)s_set',
                to='accounts.company',
                verbose_name='Société',
            ),
            preserve_default=False,
        ),
    ]
