# Generated by Django 6.0.4 on 2026-04-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('offres', '0003_offre_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='experience_requise',
            field=models.PositiveIntegerField(
                default=0, verbose_name='Expérience requise (années)'
            ),
        ),
    ]
