# Generated by Django 4.2.30 on 2026-04-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offres", "0004_offre_experience_requise"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offre",
            name="company",
        ),
    ]
