# Generated by Django 6.0.4 on 2026-04-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0006_auditlog_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('recipient', models.EmailField(max_length=254, verbose_name='Destinataire')),
                (
                    'type',
                    models.CharField(
                        choices=[('EMAIL', 'Email'), ('SMS', 'SMS')],
                        max_length=10,
                        verbose_name='Type',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('SENT', 'Envoyé'),
                            ('FAILED', 'Échoué'),
                            ('PENDING', 'En attente'),
                        ],
                        default='PENDING',
                        max_length=10,
                        verbose_name='Statut',
                    ),
                ),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Tentatives')),
                (
                    'error_message',
                    models.TextField(blank=True, null=True, verbose_name="Message d'erreur"),
                ),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_set',
                        to='accounts.company',
                        verbose_name='Société',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Journal de notification',
                'verbose_name_plural': 'Journaux de notifications',
                'ordering': ['-timestamp'],
            },
        ),
    ]
