# Generated by Django 4.2.30 on 2026-04-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationlog",
            name="company",
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="attempts",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Tentatives"
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="recipient",
            field=models.CharField(max_length=255, verbose_name="Destinataire"),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="type",
            field=models.CharField(
                choices=[("EMAIL", "Email"), ("SMS", "SMS")],
                default="EMAIL",
                max_length=10,
                verbose_name="Type",
            ),
        ),
    ]
