# Generated by Django 6.0.4 on 2026-04-13 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('CREATE', 'Création'),
                            ('UPDATE', 'Modification'),
                            ('DELETE', 'Suppression'),
                            ('VIEW', 'Consultation'),
                        ],
                        max_length=10,
                        verbose_name='Action',
                    ),
                ),
                ('model_name', models.CharField(max_length=100, verbose_name='Modèle')),
                (
                    'object_id',
                    models.IntegerField(blank=True, null=True, verbose_name='ID objet'),
                ),
                (
                    'data_before',
                    models.JSONField(blank=True, null=True, verbose_name='Données avant'),
                ),
                (
                    'data_after',
                    models.JSONField(blank=True, null=True, verbose_name='Données après'),
                ),
                (
                    'ip_address',
                    models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
                ),
                (
                    'user_agent',
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name='User-Agent'
                    ),
                ),
                (
                    'timestamp',
                    models.DateTimeField(auto_now_add=True, verbose_name='Horodatage'),
                ),
                (
                    'endpoint',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='Endpoint'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='audit_logs',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Utilisateur',
                    ),
                ),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(
                        fields=['user', 'timestamp'],
                        name='accounts_au_user_id_d4cccd_idx',
                    ),
                    models.Index(
                        fields=['model_name', 'action'],
                        name='accounts_au_model_n_dc0fe1_idx',
                    ),
                ],
            },
        ),
    ]
