# Generated by Django 6.0.4 on 2026-04-17 00:58

from django.db import migrations


def assign_default_company(apps, schema_editor):
    """
    Create a 'Default Organization' company and assign all existing users
    who have no company to it.
    """
    Company = apps.get_model('accounts', 'Company')
    User = apps.get_model('accounts', 'User')

    default_company, _ = Company.objects.get_or_create(
        slug='default-organization',
        defaults={
            'name': 'Default Organization',
            'is_active': True,
        },
    )

    # Assign all users without a company to the default one
    User.objects.filter(company__isnull=True).update(company=default_company)


def remove_default_company(apps, schema_editor):
    """
    Reverse: un-assign users from the default company and delete it.
    """
    Company = apps.get_model('accounts', 'Company')
    User = apps.get_model('accounts', 'User')

    try:
        default_company = Company.objects.get(slug='default-organization')
        User.objects.filter(company=default_company).update(company=None)
        default_company.delete()
    except Company.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_company_user_company'),
    ]

    operations = [
        migrations.RunPython(assign_default_company, remove_default_company),
    ]
