# Generated by Django 4.2.30 on 2026-04-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offres", "0005_remove_offre_company"),
        ("statistiques", "0002_alter_kpisnapshot_unique_together_and_more"),
        ("notifications", "0002_remove_notificationlog_company_and_more"),
        ("entretiens", "0006_remove_entretien_company"),
        ("candidatures", "0005_remove_candidature_company"),
        ("evaluations", "0005_remove_evaluation_company"),
        ("accounts", "0006_auditlog_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditlog",
            name="company",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company",
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
